apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: a0005-i
resources:
- networkpolicy.yaml
- deployment.yaml
- allowed-traffic.yaml
images:
- name: acraksite2hif2xfui4.azurecr.us/live/a0005/chain-api
  newName: acraksite2hif2xfui4.azurecr.us/live/a0005/chain-api