apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aks-ingress-contoso-com-tls-secret-csi-akv
spec:
  provider: azure
  secretObjects:
  - secretName: ingress-tls-csi
    type: kubernetes.io/tls
    data:
    - objectName: ingress-internal-aks-ingress-contoso-com-tls
      key: tls.key
    - objectName: ingress-internal-aks-ingress-contoso-com-tls
      key: tls.crt
  parameters:
    clientID: 8cc56d6b-82da-4d71-a742-e3c1c2fe2e66
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: kv-aks-ite2hif2xfui4
    objects: |
      array:
        - |
          objectName: ingress-internal-aks-ingress-contoso-com-tls
          objectType: secret
    tenantID: 
