apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
resources:
- namespace.yaml
- akv-tls-provider.yaml
- deployment.yaml
images:
- name: acraksite2hif2xfui4.azurecr.us/live/ingress-nginx/kube-webhook-certgen
  newName: acraksite2hif2xfui4.azurecr.us/live/ingress-nginx/kube-webhook-certgen
- name: acraksite2hif2xfui4.azurecr.us/live/ingress-nginx/controller
  newName: acraksite2hif2xfui4.azurecr.us/live/ingress-nginx/controller