apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: falco-system
resources:
- namespace.yaml
- limit-range.yaml
- resource-quota.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- serviceaccount.yaml
- configmap.yaml
- daemonset.yaml
- falcoctl-configmap.yaml
images:
- name: docker.io/falcosecurity/falco-no-driver
  newName: acraksite2hif2xfui4.azurecr.us/live/falcosecurity/falco-no-driver
- name: docker.io/falcosecurity/falco-driver-loader
  newName: acraksite2hif2xfui4.azurecr.us/live/falcosecurity/falco-driver-loader
- name: docker.io/falcosecurity/falcoctl
  newName: acraksite2hif2xfui4.azurecr.us/live/falcosecurity/falcoctl